// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace cmv.tecnologia.Tests.NotificationService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ArchivoAdjunto
    {
        /// <summary>
        /// Initializes a new instance of the ArchivoAdjunto class.
        /// </summary>
        public ArchivoAdjunto() { }

        /// <summary>
        /// Initializes a new instance of the ArchivoAdjunto class.
        /// </summary>
        public ArchivoAdjunto(byte[] archivo = default(byte[]), string nombre = default(string))
        {
            Archivo = archivo;
            Nombre = nombre;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Archivo")]
        public byte[] Archivo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nombre")]
        public string Nombre { get; set; }

    }
}
