// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace cmv.tecnologia.Tests.NotificationService.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SmsNotification
    {
        /// <summary>
        /// Initializes a new instance of the SmsNotification class.
        /// </summary>
        public SmsNotification() { }

        /// <summary>
        /// Initializes a new instance of the SmsNotification class.
        /// </summary>
        public SmsNotification(string message = default(string), string phone = default(string))
        {
            Message = message;
            Phone = phone;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

    }
}
