//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmv.tecnologia.DAL.WsCalixtaV4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.calixtaondemand.com", ConfigurationName="WsCalixtaV4.GatewayPortType")]
    public interface GatewayPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensajes(cmv.tecnologia.DAL.WsCalixtaV4.Transaccion mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajesAsync(cmv.tecnologia.DAL.WsCalixtaV4.Transaccion mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvioEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EstadoEnvioEmail(int cte, string email, string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvioEmail", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EstadoEnvioEmailAsync(int cte, string email, string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EventosEnvioEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailResponse EventosEnvioEmail(cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EventosEnvioEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailResponse> EventosEnvioEmailAsync(cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string EnviaEmail(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaEmail", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> EnviaEmailAsync(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajesCSV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensajesCSV(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionCSV mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajesCSV", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajesCSVAsync(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionCSV mensajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensaje(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensaje", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajeAsync(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        cmv.tecnologia.DAL.WsCalixtaV4.RespEnvio EstadoEnvio(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoEnvio", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.RespEnvio> EstadoEnvioAsync(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        cmv.tecnologia.DAL.WsCalixtaV4.EdoMensajes[] EstadoMensajes(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EdoMensajes[]> EstadoMensajesAsync(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EnviaMensajeOL(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOL", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EnviaMensajeOLAsync(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOLRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefResponse EnviaMensajeOLRef(cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EnviaMensajeOLRef", ReplyAction="*")]
        System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefResponse> EnviaMensajeOLRefAsync(cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EstadoMensajeOLRef(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRef", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EstadoMensajeOLRefAsync(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRefAux", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxResponse EstadoMensajeOLAux(cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EstadoMensajeOLRefAux", ReplyAction="*")]
        System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxResponse> EstadoMensajeOLAuxAsync(cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaALista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int AgregaALista(int idCliente, string email, string password, int idLista, string telefono, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#AgregaALista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> AgregaAListaAsync(int idCliente, string email, string password, int idLista, string telefono, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ExisteEnLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int ExisteEnLista(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ExisteEnLista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> ExisteEnListaAsync(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EliminaDeLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int EliminaDeLista(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#EliminaDeLista", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> EliminaDeListaAsync(int idCliente, string email, string password, int idLista, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Saldos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdoMensajes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Eventos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Mensaje))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        cmv.tecnologia.DAL.WsCalixtaV4.Saldos[] ConsultaSaldo(int idCliente, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.calixtaondemand.com#ConsultaSaldo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.Saldos[]> ConsultaSaldoAsync(int idCliente, string email, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Transaccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private string tipoField;
        
        private string fechaHoraField;
        
        private Mensaje[] mensajesField;
        
        private int idivrField;
        
        /// <remarks/>
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        public Mensaje[] mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
                this.RaisePropertyChanged("mensajes");
            }
        }
        
        /// <remarks/>
        public int idivr {
            get {
                return this.idivrField;
            }
            set {
                this.idivrField = value;
                this.RaisePropertyChanged("idivr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Mensaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefonoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Saldos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string servicioField;
        
        private double disponibleField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
        
        /// <remarks/>
        public double disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
                this.RaisePropertyChanged("disponible");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class EdoMensajes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string telefonoField;
        
        private double costoField;
        
        private string fechaHoraField;
        
        private string estadoField;
        
        private string listaField;
        
        private int idEnvioField;
        
        private int idEstadoField;
        
        private string mensajeField;
        
        private string destinoField;
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        public string lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        /// <remarks/>
        public int idEnvio {
            get {
                return this.idEnvioField;
            }
            set {
                this.idEnvioField = value;
                this.RaisePropertyChanged("idEnvio");
            }
        }
        
        /// <remarks/>
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("destino");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class RespEnvio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private double fInicioField;
        
        private string camposField;
        
        private string descripcionField;
        
        private string listaField;
        
        private double porField;
        
        private int tipoField;
        
        private int idUsuarioField;
        
        private int especieField;
        
        private int estadoField;
        
        private double costoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public double fInicio {
            get {
                return this.fInicioField;
            }
            set {
                this.fInicioField = value;
                this.RaisePropertyChanged("fInicio");
            }
        }
        
        /// <remarks/>
        public string campos {
            get {
                return this.camposField;
            }
            set {
                this.camposField = value;
                this.RaisePropertyChanged("campos");
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        public string lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        /// <remarks/>
        public double por {
            get {
                return this.porField;
            }
            set {
                this.porField = value;
                this.RaisePropertyChanged("por");
            }
        }
        
        /// <remarks/>
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        public int especie {
            get {
                return this.especieField;
            }
            set {
                this.especieField = value;
                this.RaisePropertyChanged("especie");
            }
        }
        
        /// <remarks/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class TransaccionEnvios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private int idEnvioField;
        
        /// <remarks/>
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public int idEnvio {
            get {
                return this.idEnvioField;
            }
            set {
                this.idEnvioField = value;
                this.RaisePropertyChanged("idEnvio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class TransaccionCSV : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idClienteField;
        
        private string emailField;
        
        private string passwordField;
        
        private string tipoField;
        
        private string fechaHoraField;
        
        private string csvField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        public string csv {
            get {
                return this.csvField;
            }
            set {
                this.csvField = value;
                this.RaisePropertyChanged("csv");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.calixtaondemand.com")]
    public partial class Eventos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string tipoField;
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventosEnvioEmail", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EventosEnvioEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string id;
        
        public EventosEnvioEmailRequest() {
        }
        
        public EventosEnvioEmailRequest(int cte, string email, string password, string id) {
            this.cte = cte;
            this.email = email;
            this.password = password;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EventosEnvioEmailResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EventosEnvioEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public cmv.tecnologia.DAL.WsCalixtaV4.Eventos[] eventos;
        
        public EventosEnvioEmailResponse() {
        }
        
        public EventosEnvioEmailResponse(int code, cmv.tecnologia.DAL.WsCalixtaV4.Eventos[] eventos) {
            this.code = code;
            this.eventos = eventos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviaMensajeOLRef", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EnviaMensajeOLRefRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int idivr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string fechaInicio;
        
        public EnviaMensajeOLRefRequest() {
        }
        
        public EnviaMensajeOLRefRequest(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.tipo = tipo;
            this.telefono = telefono;
            this.mensaje = mensaje;
            this.idivr = idivr;
            this.fechaInicio = fechaInicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnviaMensajeOLRefResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EnviaMensajeOLRefResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string referencia;
        
        public EnviaMensajeOLRefResponse() {
        }
        
        public EnviaMensajeOLRefResponse(int resultado, string referencia) {
            this.resultado = resultado;
            this.referencia = referencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadoMensajeOLAux", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EstadoMensajeOLAuxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string campoAux;
        
        public EstadoMensajeOLAuxRequest() {
        }
        
        public EstadoMensajeOLAuxRequest(int idCliente, string email, string password, string campoAux) {
            this.idCliente = idCliente;
            this.email = email;
            this.password = password;
            this.campoAux = campoAux;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadoMensajeOLAuxResponse", WrapperNamespace="http://www.calixtaondemand.com", IsWrapped=true)]
    public partial class EstadoMensajeOLAuxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string id;
        
        public EstadoMensajeOLAuxResponse() {
        }
        
        public EstadoMensajeOLAuxResponse(int resultado, string referencia, string id) {
            this.resultado = resultado;
            this.referencia = referencia;
            this.id = id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewayPortTypeChannel : cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayPortTypeClient : System.ServiceModel.ClientBase<cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType>, cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType {
        
        public GatewayPortTypeClient() {
        }
        
        public GatewayPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int EnviaMensajes(cmv.tecnologia.DAL.WsCalixtaV4.Transaccion mensajes) {
            return base.Channel.EnviaMensajes(mensajes);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajesAsync(cmv.tecnologia.DAL.WsCalixtaV4.Transaccion mensajes) {
            return base.Channel.EnviaMensajesAsync(mensajes);
        }
        
        public int EstadoEnvioEmail(int cte, string email, string password, int id) {
            return base.Channel.EstadoEnvioEmail(cte, email, password, id);
        }
        
        public System.Threading.Tasks.Task<int> EstadoEnvioEmailAsync(int cte, string email, string password, int id) {
            return base.Channel.EstadoEnvioEmailAsync(cte, email, password, id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailResponse cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType.EventosEnvioEmail(cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailRequest request) {
            return base.Channel.EventosEnvioEmail(request);
        }
        
        public int EventosEnvioEmail(int cte, string email, string password, string id, out cmv.tecnologia.DAL.WsCalixtaV4.Eventos[] eventos) {
            cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailRequest inValue = new cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailRequest();
            inValue.cte = cte;
            inValue.email = email;
            inValue.password = password;
            inValue.id = id;
            cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailResponse retVal = ((cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType)(this)).EventosEnvioEmail(inValue);
            eventos = retVal.eventos;
            return retVal.code;
        }
        
        public System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailResponse> EventosEnvioEmailAsync(cmv.tecnologia.DAL.WsCalixtaV4.EventosEnvioEmailRequest request) {
            return base.Channel.EventosEnvioEmailAsync(request);
        }
        
        public string EnviaEmail(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar) {
            return base.Channel.EnviaEmail(cte, email, password, nombreCamp, to, from, fromName, replyTo, subject, incrustarImagen, textEmail, htmlEmail, seleccionaAdjuntos, fileBase64, fileNameBase64, nombreArchivoPersonalizado, envioSinArchivo, fechaInicio, horaInicio, minutoInicio, listasNegras, referencia, campoAuxiliar);
        }
        
        public System.Threading.Tasks.Task<string> EnviaEmailAsync(
                    int cte, 
                    string email, 
                    string password, 
                    string nombreCamp, 
                    string to, 
                    string from, 
                    string fromName, 
                    string replyTo, 
                    string subject, 
                    int incrustarImagen, 
                    string textEmail, 
                    string htmlEmail, 
                    int seleccionaAdjuntos, 
                    byte[] fileBase64, 
                    string fileNameBase64, 
                    string nombreArchivoPersonalizado, 
                    int envioSinArchivo, 
                    string fechaInicio, 
                    int horaInicio, 
                    int minutoInicio, 
                    string listasNegras, 
                    string referencia, 
                    string campoAuxiliar) {
            return base.Channel.EnviaEmailAsync(cte, email, password, nombreCamp, to, from, fromName, replyTo, subject, incrustarImagen, textEmail, htmlEmail, seleccionaAdjuntos, fileBase64, fileNameBase64, nombreArchivoPersonalizado, envioSinArchivo, fechaInicio, horaInicio, minutoInicio, listasNegras, referencia, campoAuxiliar);
        }
        
        public int EnviaMensajesCSV(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionCSV mensajes) {
            return base.Channel.EnviaMensajesCSV(mensajes);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajesCSVAsync(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionCSV mensajes) {
            return base.Channel.EnviaMensajesCSVAsync(mensajes);
        }
        
        public int EnviaMensaje(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr) {
            return base.Channel.EnviaMensaje(idCliente, email, password, tipo, fechaHora, telefono, mensaje, idivr);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajeAsync(int idCliente, string email, string password, string tipo, string fechaHora, string telefono, string mensaje, int idivr) {
            return base.Channel.EnviaMensajeAsync(idCliente, email, password, tipo, fechaHora, telefono, mensaje, idivr);
        }
        
        public cmv.tecnologia.DAL.WsCalixtaV4.RespEnvio EstadoEnvio(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoEnvio(idEnvio);
        }
        
        public System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.RespEnvio> EstadoEnvioAsync(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoEnvioAsync(idEnvio);
        }
        
        public cmv.tecnologia.DAL.WsCalixtaV4.EdoMensajes[] EstadoMensajes(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoMensajes(idEnvio);
        }
        
        public System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EdoMensajes[]> EstadoMensajesAsync(cmv.tecnologia.DAL.WsCalixtaV4.TransaccionEnvios idEnvio) {
            return base.Channel.EstadoMensajesAsync(idEnvio);
        }
        
        public int EnviaMensajeOL(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio) {
            return base.Channel.EnviaMensajeOL(idCliente, email, password, tipo, telefono, mensaje, idivr, fechaInicio);
        }
        
        public System.Threading.Tasks.Task<int> EnviaMensajeOLAsync(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio) {
            return base.Channel.EnviaMensajeOLAsync(idCliente, email, password, tipo, telefono, mensaje, idivr, fechaInicio);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefResponse cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType.EnviaMensajeOLRef(cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefRequest request) {
            return base.Channel.EnviaMensajeOLRef(request);
        }
        
        public int EnviaMensajeOLRef(int idCliente, string email, string password, string tipo, string telefono, string mensaje, int idivr, string fechaInicio, out string referencia) {
            cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefRequest inValue = new cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefRequest();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            inValue.tipo = tipo;
            inValue.telefono = telefono;
            inValue.mensaje = mensaje;
            inValue.idivr = idivr;
            inValue.fechaInicio = fechaInicio;
            cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefResponse retVal = ((cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType)(this)).EnviaMensajeOLRef(inValue);
            referencia = retVal.referencia;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefResponse> EnviaMensajeOLRefAsync(cmv.tecnologia.DAL.WsCalixtaV4.EnviaMensajeOLRefRequest request) {
            return base.Channel.EnviaMensajeOLRefAsync(request);
        }
        
        public int EstadoMensajeOLRef(string referencia) {
            return base.Channel.EstadoMensajeOLRef(referencia);
        }
        
        public System.Threading.Tasks.Task<int> EstadoMensajeOLRefAsync(string referencia) {
            return base.Channel.EstadoMensajeOLRefAsync(referencia);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxResponse cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType.EstadoMensajeOLAux(cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxRequest request) {
            return base.Channel.EstadoMensajeOLAux(request);
        }
        
        public int EstadoMensajeOLAux(int idCliente, string email, string password, string campoAux, out string referencia, out string id) {
            cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxRequest inValue = new cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxRequest();
            inValue.idCliente = idCliente;
            inValue.email = email;
            inValue.password = password;
            inValue.campoAux = campoAux;
            cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxResponse retVal = ((cmv.tecnologia.DAL.WsCalixtaV4.GatewayPortType)(this)).EstadoMensajeOLAux(inValue);
            referencia = retVal.referencia;
            id = retVal.id;
            return retVal.resultado;
        }
        
        public System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxResponse> EstadoMensajeOLAuxAsync(cmv.tecnologia.DAL.WsCalixtaV4.EstadoMensajeOLAuxRequest request) {
            return base.Channel.EstadoMensajeOLAuxAsync(request);
        }
        
        public int AgregaALista(int idCliente, string email, string password, int idLista, string telefono, string nombre) {
            return base.Channel.AgregaALista(idCliente, email, password, idLista, telefono, nombre);
        }
        
        public System.Threading.Tasks.Task<int> AgregaAListaAsync(int idCliente, string email, string password, int idLista, string telefono, string nombre) {
            return base.Channel.AgregaAListaAsync(idCliente, email, password, idLista, telefono, nombre);
        }
        
        public int ExisteEnLista(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.ExisteEnLista(idCliente, email, password, idLista, telefono);
        }
        
        public System.Threading.Tasks.Task<int> ExisteEnListaAsync(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.ExisteEnListaAsync(idCliente, email, password, idLista, telefono);
        }
        
        public int EliminaDeLista(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.EliminaDeLista(idCliente, email, password, idLista, telefono);
        }
        
        public System.Threading.Tasks.Task<int> EliminaDeListaAsync(int idCliente, string email, string password, int idLista, string telefono) {
            return base.Channel.EliminaDeListaAsync(idCliente, email, password, idLista, telefono);
        }
        
        public cmv.tecnologia.DAL.WsCalixtaV4.Saldos[] ConsultaSaldo(int idCliente, string email, string password) {
            return base.Channel.ConsultaSaldo(idCliente, email, password);
        }
        
        public System.Threading.Tasks.Task<cmv.tecnologia.DAL.WsCalixtaV4.Saldos[]> ConsultaSaldoAsync(int idCliente, string email, string password) {
            return base.Channel.ConsultaSaldoAsync(idCliente, email, password);
        }
    }
}
