// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace cmv.tecnologia.Tests.NotificationService
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Notification operations.
    /// </summary>
    public partial interface INotification
    {
        /// <summary>
        /// Envia mensaje de texto de CMV
        /// </summary>
        /// <param name='request'>
        /// </param>
        /// <param name='authorization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> SendSmsNotificationTextMessageWithHttpMessagesAsync(SmsNotification request, string authorization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Envia mensaje de correo desde Cmv Finanzas
        /// </summary>
        /// <param name='request'>
        /// </param>
        /// <param name='authorization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> SendEMailNotificationMessageCmvWithHttpMessagesAsync(EmailNotification request, string authorization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Envia mensaje de correo desde Robot Cmv
        /// </summary>
        /// <param name='request'>
        /// </param>
        /// <param name='authorization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> SendLocalEMailNotificationMessageWithHttpMessagesAsync(EmailNotification request, string authorization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Envia mensaje de correo
        /// </summary>
        /// <param name='request'>
        /// </param>
        /// <param name='authorization'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> SendEMailNotificationMessageWithHttpMessagesAsync(EmailNotification request, string authorization = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
